"""
Xata Database Migration Script V2
Enhanced version with better error handling and SDK integration

Usage:
    python migrate_v2.py --setup      # Interactive setup wizard
    python migrate_v2.py --create     # Create all tables
    python migrate_v2.py --status     # Check database status
    python migrate_v2.py --validate   # Validate schema against DepMap files
"""

import os
import json
import argparse
from pathlib import Path
from dotenv import load_dotenv
import pandas as pd

# Load environment variables
load_dotenv()

XATA_API_KEY = os.getenv("XATA_API_KEY")
XATA_DB_URL = os.getenv("XATA_DB_URL")


class Colors:
    """ANSI color codes for pretty printing"""

    HEADER = "\033[95m"
    OKBLUE = "\033[94m"
    OKCYAN = "\033[96m"
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    BOLD = "\033[1m"


def print_header(text):
    print(f"\n{Colors.BOLD}{Colors.HEADER}{text}{Colors.ENDC}")
    print("=" * 70)


def print_success(text):
    print(f"{Colors.OKGREEN}✅ {text}{Colors.ENDC}")


def print_error(text):
    print(f"{Colors.FAIL}❌ {text}{Colors.ENDC}")


def print_warning(text):
    print(f"{Colors.WARNING}⚠️  {text}{Colors.ENDC}")


def print_info(text):
    print(f"{Colors.OKCYAN}ℹ️  {text}{Colors.ENDC}")


def load_schema():
    """Load schema from JSON file"""
    schema_path = Path(__file__).parent / "xata_schema.json"
    with open(schema_path, "r") as f:
        return json.load(f)


def check_dependencies():
    """Check if required dependencies are installed"""
    print_header("Checking Dependencies")

    all_good = True

    # Check Xata SDK
    try:
        from xata.client import XataClient

        print_success("Xata Python SDK installed")
    except ImportError:
        print_error("Xata Python SDK not installed")
        print("   Install with: pip install xata")
        all_good = False

    # Check pandas
    try:
        import pandas as pd

        print_success("pandas installed")
    except ImportError:
        print_error("pandas not installed")
        print("   Install with: pip install pandas")
        all_good = False

    # Check environment variables
    if XATA_API_KEY and XATA_API_KEY != "your_api_key_here":
        print_success("XATA_API_KEY configured")
    else:
        print_error("XATA_API_KEY not configured")
        all_good = False

    if (
        XATA_DB_URL
        and XATA_DB_URL != "https://your_workspace.xata.sh/db/starx-therapeutics"
    ):
        print_success("XATA_DB_URL configured")
    else:
        print_error("XATA_DB_URL not configured")
        all_good = False

    return all_good


def setup_wizard():
    """Interactive setup wizard"""
    print_header("Xata Setup Wizard")

    env_path = Path(__file__).parent.parent.parent / ".env"

    print("\n📝 This wizard will help you set up your Xata database.")
    print("\n" + "─" * 70)

    # Step 1: Account check
    print("\n1️⃣  Xata Account Setup")
    has_account = input("   Do you have a Xata account? (y/n): ").lower()
    if has_account != "y":
        print_info("Go to https://xata.io and sign up for a free account")
        print_info("After signing up, come back and run this wizard again")
        return

    # Step 2: Database creation
    print("\n2️⃣  Database Setup")
    print_info("Log in to Xata: https://app.xata.io")
    print_info("1. Click 'New Database'")
    print_info("2. Name it: starx-therapeutics")
    print_info("3. Select any region (US East recommended)")

    db_created = input("\n   Have you created the database? (y/n): ").lower()
    if db_created != "y":
        print_warning("Create the database first, then come back")
        return

    # Step 3: API Key
    print("\n3️⃣  API Key Setup")
    print_info("In Xata UI, go to: Account Settings → API Keys")
    print_info("Click 'Add API Key' and copy the key")

    api_key = input("\n   Paste your API key here: ").strip()

    # Step 4: Database URL
    print("\n4️⃣  Database URL")
    print_info("In Xata UI, go to your database settings")
    print_info("Look for 'Database URL' or construct it:")
    print_info("Format: https://YOUR_WORKSPACE.xata.sh/db/starx-therapeutics")

    db_url = input("\n   Paste your database URL: ").strip()

    # Step 5: Save to .env
    print("\n5️⃣  Saving Configuration")

    env_content = f"""# Xata Database Configuration
# Generated by migration wizard
XATA_API_KEY={api_key}
XATA_DB_URL={db_url}
"""

    with open(env_path, "w") as f:
        f.write(env_content)

    print_success(f"Configuration saved to {env_path}")

    # Step 6: Verify
    print("\n6️⃣  Verifying Connection")
    os.environ["XATA_API_KEY"] = api_key
    os.environ["XATA_DB_URL"] = db_url

    try:
        from xata.client import XataClient

        client = XataClient(api_key=api_key, db_url=db_url)
        # Test connection by getting database info
        print_success("Connection successful!")
        print("\n" + "─" * 70)
        print_success("Setup complete! Run: python migrate_v2.py --create")
    except Exception as e:
        print_error(f"Connection failed: {e}")
        print_warning("Please check your API key and database URL")


def create_tables():
    """Create all tables using Xata Python SDK"""
    print_header("Creating Xata Tables")

    if not check_dependencies():
        print_error("Please fix dependencies first")
        return False

    from xata.client import XataClient

    client = XataClient(api_key=XATA_API_KEY, db_url=XATA_DB_URL)
    schema = load_schema()

    print(f"\nCreating {len(schema['tables'])} tables...\n")

    # Xata type mapping
    type_mapping = {
        "string": "string",
        "text": "text",
        "int": "int",
        "float": "float",
        "bool": "bool",
        "datetime": "datetime",
        "json": "json",
        "multiple": "multiple",
    }

    for table in schema["tables"]:
        table_name = table["name"]
        print(f"\n Table: {Colors.BOLD}{table_name}{Colors.ENDC}")

        # Prepare columns for Xata
        columns = []
        for col in table["columns"]:
            xata_type = type_mapping.get(col["type"], "string")
            columns.append({"name": col["name"], "type": xata_type})

        try:
            # Create table with columns
            # Note: This uses the Xata API format
            payload = {"name": table_name, "columns": columns}

            # Use direct API call for table creation
            import requests

            # Extract host and database name from DB URL
            # URL format: https://workspace.region.xata.tech/db/database-name
            url_parts = XATA_DB_URL.split("/db/")
            base_url = url_parts[0]  # https://workspace.region.xata.tech
            db_name = url_parts[1]  # database-name

            api_url = f"{base_url}/db/{db_name}/tables"

            headers = {
                "Authorization": f"Bearer {XATA_API_KEY}",
                "Content-Type": "application/json",
            }

            response = requests.post(api_url, json=payload, headers=headers)

            if response.status_code == 201:
                print_success(f"Created with {len(columns)} columns")
                for col in columns[:5]:  # Show first 5 columns
                    print(f"   • {col['name']:30s} ({col['type']})")
                if len(columns) > 5:
                    print(f"   • ... and {len(columns) - 5} more columns")
            elif response.status_code == 409:
                print_warning(f"Already exists, skipping")
            else:
                print_error(f"Failed: {response.text}")

        except Exception as e:
            print_error(f"Error: {e}")

    print("\n" + "─" * 70)
    print_success("Table creation complete!")
    print_info("Next step: Verify tables at https://app.xata.io")

    return True


def check_status():
    """Check database and table status"""
    print_header("Database Status")

    if not check_dependencies():
        return

    schema = load_schema()

    print(f"\n Expected Schema ({len(schema['tables'])} tables):\n")

    total_columns = 0
    for table in schema["tables"]:
        col_count = len(table["columns"])
        total_columns += col_count
        print(f"   • {table['name']:35s} {col_count:2d} columns")

    print(f"\n   Total: {len(schema['tables'])} tables, {total_columns} columns")

    # Try to connect and list actual tables
    try:
        from xata.client import XataClient
        import requests

        # Extract host and database name from DB URL
        # URL format: https://workspace.region.xata.tech/db/database-name
        url_parts = XATA_DB_URL.split("/db/")
        base_url = url_parts[0]  # https://workspace.region.xata.tech
        db_name = url_parts[1]  # database-name

        api_url = f"{base_url}/db/{db_name}/tables"

        headers = {
            "Authorization": f"Bearer {XATA_API_KEY}",
            "Content-Type": "application/json",
        }

        response = requests.get(api_url, headers=headers)

        if response.status_code == 200:
            tables = response.json().get("tables", [])
            print(f"\n✅ Actual Database ({len(tables)} tables):\n")
            for table in tables:
                print(f"   • {table['name']}")
        else:
            print_warning("Could not fetch actual tables from Xata")

    except Exception as e:
        print_warning(f"Could not connect to Xata: {e}")


def validate_against_depmap():
    """Validate schema against downloaded DepMap files"""
    print_header("Validating Schema Against DepMap Files")

    data_dir = Path(__file__).parent.parent.parent / "data" / "raw" / "depmap"

    if not data_dir.exists():
        print_error(f"DepMap data directory not found: {data_dir}")
        return

    print("\n📁 Checking DepMap Files:\n")

    # Check for expected files
    expected_files = {
        "CRISPRGeneEffect.csv": "Gene effect scores (dependency)",
        "CRISPRGeneDependency.csv": "Gene dependency probabilities",
        "Model.csv": "Cell line metadata",
        "OmicsExpressionTPMLogp1HumanProteinCodingGenes.csv": "Gene expression",
        "OmicsCNGeneWGS.csv": "Copy number variations",
        "OmicsSomaticMutationsMatrixDamaging.csv": "Damaging mutations",
        "OmicsSomaticMutationsMatrixHotspot.csv": "Hotspot mutations",
    }

    files_found = 0
    for filename, description in expected_files.items():
        filepath = data_dir / filename
        if filepath.exists():
            size_mb = filepath.stat().st_size / (1024 * 1024)
            print_success(f"{filename}")
            print(f"        {description} ({size_mb:.1f} MB)")
            files_found += 1
        else:
            print_warning(f"{filename} - NOT FOUND")

    print(f"\n Found {files_found}/{len(expected_files)} expected files")

    # Validate target genes in schema
    print("\n Validating Target Genes in Schema:\n")

    schema = load_schema()
    multi_target_table = next(
        (t for t in schema["tables"] if t["name"] == "multi_target_dependencies"), None
    )

    if multi_target_table:
        target_genes = []
        for col in multi_target_table["columns"]:
            if "_dependency" in col["name"] and col["name"] != "combined_score":
                gene = col["name"].replace("_dependency", "")
                target_genes.append(gene)

        print_info(f"Schema includes {len(target_genes)} target genes:")
        for gene in target_genes:
            print(f"   • {gene}")

        # Check if target genes exist in DepMap data
        effect_file = data_dir / "CRISPRGeneEffect.csv"
        if effect_file.exists():
            print("\n🔍 Checking target genes in DepMap data...")
            try:
                # Read just the header
                df_head = pd.read_csv(effect_file, nrows=0)
                columns = df_head.columns.tolist()

                genes_in_data = []
                for col in columns:
                    if " " in col:  # DepMap format: "GENE (ENTREZ_ID)"
                        gene = col.split(" ")[0]
                        genes_in_data.append(gene)

                for gene in target_genes:
                    if gene in genes_in_data:
                        print_success(f"{gene} found in DepMap data")
                    else:
                        print_warning(f"{gene} NOT found in DepMap data (check naming)")

            except Exception as e:
                print_error(f"Could not read DepMap file: {e}")

    print("\n" + "─" * 70)
    print_success("Validation complete!")


def main():
    parser = argparse.ArgumentParser(
        description="Xata Database Migration Tool V2",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--setup", action="store_true", help="Interactive setup wizard")
    parser.add_argument("--create", action="store_true", help="Create all tables")
    parser.add_argument("--status", action="store_true", help="Check database status")
    parser.add_argument(
        "--validate", action="store_true", help="Validate schema against DepMap files"
    )

    args = parser.parse_args()

    print(f"\n{Colors.BOLD}{Colors.HEADER}")
    print("╔═══════════════════════════════════════════════════════════════════╗")
    print("║  Xata Migration Tool V2 - StarX Therapeutics Analysis            ║")
    print("╚═══════════════════════════════════════════════════════════════════╝")
    print(Colors.ENDC)

    if args.setup:
        setup_wizard()
    elif args.create:
        create_tables()
    elif args.status:
        check_status()
    elif args.validate:
        validate_against_depmap()
    else:
        parser.print_help()
        print("\n Quick Start:")
        print(
            f"   {Colors.OKGREEN}python migrate_v2.py --setup{Colors.ENDC}      # First-time setup"
        )
        print(
            f"   {Colors.OKGREEN}python migrate_v2.py --validate{Colors.ENDC}   # Check DepMap files"
        )
        print(
            f"   {Colors.OKGREEN}python migrate_v2.py --create{Colors.ENDC}     # Create tables"
        )
        print(
            f"   {Colors.OKGREEN}python migrate_v2.py --status{Colors.ENDC}     # Check status"
        )
        print()


if __name__ == "__main__":
    main()
